### ISSUE TITLE
Search for shows

### ISSUE THREAD

**Issue by codexbella** [codexbella/watcher#2]
Backend:
- [x] api search request #6 #7
------------------------------------------
Frontend:
- [x] input option for search parameters #8
- [x] display of search results #8
