### ISSUE TITLE
Getting and displaying remaining content for shows

### ISSUE THREAD

**Issue by codexbella** [codexbella/watcher#31]
- [x] Getting season info #35 
- [x] Getting episode info #35 
- [x] Endpoints #35 
-------------------------------
- [x] Displaying season info #36 
- [x] Displaying episode info #36
